### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by michaelrbock**
Note --> Notes :smiley:

### CODE REVIEW

**Comment by rhc2104** [comment]
There are two instances of "Note:" followed by multiple notes.  So if you would like that change, you should be consistent and change it in both places.

Thanks!

**Comment by michaelrbock** [comment]
Good point! Fixed.

**Comment by rhc2104** [comment]
Hi,

After thinking about this for a while, I have decided to not go with the change.

The "Note:" is telling the user to note the following things.

As in, "Note: You should do X, Y, and Z"
Rather than, "Here are notes X, Y, and Z"

**Comment by rhc2104** [comment]
Thanks, though!

**Pull request closed without merging**
