### PR TITLE
Typo fix (Lesson 23)

### PR DESCRIPTION
**Pull request by cpursley**

### CODE REVIEW

**Comment by rhc2104** [comment]
Thanks!

**Comment by cpursley** [comment]
No problem, sqlteaching was very helpful. Are there any additional planned chapters?

I also came across http://sqlbolt.com/ ~ perhaps both projects could combine their powers?

**Comment by rhc2104** [comment]
There are no additional planned chapters, but feel free to let me know if you think any useful read queries supported by SQLite are missing!

As far as I know, SQL Bolt is not open source, so I can't just merge them.  But since SQL Teaching is open source, they can use its code or content if they wish.

**Comment by cpursley** [comment]
Yeah, I was not able to find a SQL Bold repository.

One thing I noticed with sqlteaching is the css formatting could be improved for a better experience. Are you open to formatting pull requests?

Also, in terms of repository code organization - if they chapters / sections were organized into their own folders, I think it would be easier for others to contribute new content.

Anyways, awesome project. Thanks for creating it.

**Comment by rhc2104** [comment]
If you have good ideas on how to improve the formatting (or other parts of the site), that would be greatly appreciated!

**Pull request merged**
